name: CI

on:  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest    
    steps:     
      - uses: actions/checkout@v3

#Fazer login no docker hub.
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

#Subir a nova imagem para o dockerhub.
      - name: Build and push Docker images        
        uses: docker/build-push-action@v3.1.1
        with:
          file: ./src/Dockerfile
          context: ./src/
          push: true
          tags: |
            gustavoconsales/kube-news:latest
            gustavoconsales/kube-news:${{github.run_number}}
            
  CD:      
    needs: [CI]
    runs-on: ubuntu-latest
    steps:     
      - uses: actions/checkout@v3

#Criar o contexto do kubectl
      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v3.0
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_CONFIG}}

#Parametros para fazer o deploy no kubernets
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v4.3
        with: 
          images: gustavoconsales/kube-news:${{github.run_number}}
          manifests: |
            k8s/deployment.yaml
            
          
          
          
